### ISSUE TITLE
<CR>  doesn't work in  lexima__newline_rules when i  map <CR> with  <expr> 

### ISSUE THREAD

**Issue by umrwifi** [cohama/lexima.vim#105] opened 2020-09-17 03:41 UTC
Here's my  config
```
if exists('*complete_info')
				inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\><CR>"
else
				inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif
```

**Comment by cohama** [comment] 2020-09-17 06:43
duplicate of #104

**Closed** 2021-11-25 16:28 UTC
