### ISSUE TITLE
neovim: rightside expansion get deleted after <ESC>

### ISSUE THREAD

**Issue by panders23** [cohama/lexima.vim#68] opened 2017-04-10 12:47 UTC
On current neovim-git expansions get deleted after pressing _g:lexima_map_escape_. Everything seems to work fine with the same configuration on vim8.

![peek](https://cloud.githubusercontent.com/assets/10464427/24862048/53d8570c-1dfb-11e7-9495-b57f361d65a4.gif)

Versions:
- neovim: NVIM v0.2.0-1193-g3a6b8c28c
- vim: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2017 14:11:23)
- distro: arch linux

**Comment by cohama** [comment] 2017-04-15 04:36
I found out this issue is caused by neovim's bug (neovim/neovim#6521)

**Comment by cohama** [comment] 2017-04-16 04:04
The bug is fixed in upstrem neovim. Please try again with latest neovim.

**Comment by panders23** [comment] 2017-04-23 15:20
Ok, everything seems to work fine. Thank you

**Closed** 2017-04-30 04:06 UTC
